Automated sha update
panosc-eu/spack-repo pull request #27
Opened 2021-05-12 09:48 UTC by julianhoersch

The workflow file `.github/workflows/SHA-version-update.yaml` uses the bash script `update-sha.sh` in the parent `.github` directory to automatically update the SHA version of a package upon PR's from Dependabot. The script uses Dependabots commit message to infer the name and the new and old version of the package. It successively downloads the new package file, creates the SHA256 and deletes the file afterwards again (is it useful to delete?). The old url in the package file is replaced by the new one and a new line including version and SHA is added above the most recent existing version. 

One doesn't need to name the downloaded package with extension etc. if not needed and deleted. 

Hope it works!

2021-05-26 08:44 UTC, RobertRosca requested changes
Nice! Tested this out by rebasing your changes onto a recent Dependabot PR, pushing the changes, and then screwing around until it worked. This is the PR I was working with: https://github.com/panosc-eu/spack-repo/pull/30

You can either read through my comments here and implement the changes I requested yourself to play around with it and get a feel for why I requested them, or just look at https://github.com/panosc-eu/spack-repo/pull/30/files and check how it's different to your branch.

2021-05-26 08:44 UTC, RobertRosca commented on .github/workflows/SHA-version-update.yaml
> +    paths: ['dependabot/pip/dot-github/dependabot/*']
I manually rebased this onto a recent dependabot created PR: https://github.com/panosc-eu/spack-repo/pull/30

Noticed that it did not run, as the condition was:

```yaml
on:
  pull_request:
    branches: [ master ]
    paths: ['dependabot/pip/dot-github/dependabot/*']
```

I think that's from me telling you the wrong thing :stuck_out_tongue: that means that it will execute on a, if a file matching the pattern in `paths` has been modified as part of the PR. This should be something like:

```suggestion
  pull_request:
    branches: ['dependabot/pip/dot-github/dependabot/*']
```

2021-05-26 08:44 UTC, RobertRosca commented on .github/workflows/SHA-version-update.yaml
> +      - run: ../bash update_sha.sh
There are a couple of different ways to do this. You can make `bash update_sha.sh` into an executable script (run `chmod +x ./bash update_sha.sh`) so that it can just be executed by being called (`.github/bash update_sha.sh`).

Or use bash to execute it like this: `bash .github/bash update_sha.sh`

2021-05-26 08:44 UTC, RobertRosca commented on .github/workflows/SHA-version-update.yaml
> +    steps:
```suggestion
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

You need to have the `actions/checkout@v2` step, otherwise the repository will not be checked out during the test, and as mentioned in my comment about the sparse checkouts, this should have fetch-depth set to 0.

2021-05-26 08:44 UTC, RobertRosca commented on .github/update-sha.sh
> +cd ../packages/
The CI executes at the root of the repository, so this relative path won't do what you expect (it'll try to go one level up, to a packages dir, which doesn't exist).

So you have a few options:

1. Change these paths to be relative to the root: `./packages/`, and execute the script from there `.github/update-sha.sh`
2. Change the paths to be relative to the script, you can use `SCRIPT_PATH=$(dirname "$(readlink -f "$0")")` to set a variable to the scripts path, then change this line to `cd $SCRIPT_PATH/../packages/`
3. Eh, maybe something like using `git rev-parse --show-toplevel` to get the full path to the repo's root, and then `cd $(rev-parse --show-toplevel)/packages/`

I think 1 is probably the simplest option, so just do:

```suggestion
cd ./packages/
```

2021-05-26 08:44 UTC, RobertRosca commented on .github/update-sha.sh
> +last_commit=$(git log --author=dependabot --pretty=oneline -1)
In the CI environment a sparse checkout is done where not all of the commit information is available, so this returns an empty string.

There are ways to work around this, however the repo is small enough that a sparse checkout is not needed, so instead the fetch depth option can be changed for the checkout action, see https://github.com/actions/checkout

2021-05-26 08:44 UTC, RobertRosca commented on .github/update-sha.sh
> +git push origin PR_branch
You'll need a bit more to get this working, it's probably easier to remove this part from the script and instead do it at the end of the run step (as in https://github.com/actions/checkout#push-a-commit-using-the-built-in-token) or to use a github push action (https://github.com/ad-m/github-push-action).

2021-05-26 09:32 UTC, julianhoersch commented on .github/workflows/SHA-version-update.yaml
> +      - run: ../bash update_sha.sh
made it executable and changed run command

2021-05-26 10:39 UTC, julianhoersch commented on .github/update-sha.sh
> +last_commit=$(git log --author=dependabot --pretty=oneline -1)
I could also change the implementation to get the needed information from the PR branch name to avoid that workaround

2021-05-26 11:39 UTC, julianhoersch commented on .github/update-sha.sh
> +git push origin PR_branch
makes sense! Haven't thought about the permissions of the action... is there any advantage in using the github push action over the other possibility?

2021-05-26 12:23 UTC, julianhoersch commented on .github/workflows/SHA-version-update.yaml
> +    paths: ['dependabot/pip/dot-github/dependabot/*']
in your example you also triggered on push https://github.com/panosc-eu/spack-repo/pull/30/files wouldn't that fail if the commit messages are not the original ones from dependabot? I' ve added an if statement now to check if the commit message contains Bump...from...to

2021-06-30 08:45 UTC, RobertRosca commented on .github/update-sha.sh
> +git push origin PR_branch
Hey, yeah, doing the push directly won't work as the token/keys required for the push to go through are not present. It's possible to set this up yourself, but just using the push action is easier

2021-06-30 09:04 UTC, RobertRosca commented
Manually rebased and did a force push to https://github.com/panosc-eu/spack-repo/pull/31

As that was a push, not a PR, the CI won't trigger, so I added a temporary line

```yaml
on:
  ...
  push:
    branches: ['dependabot/pip/dot-github/dependabot/*']
```

To trigger the CI on pushes as well.

The script failed but the output wasn't very clear on why, so I also added `set -x` to the `update-sha.sh` script, this option makes it print every execution out as the script runs, which is very useful for debugging, it showed:

```
  ./.github/update-sha.sh
  shell: /usr/bin/bash -e {0}
++ git log --author=dependabot --pretty=oneline -1
+ last_commit='caabc5af30b2d92e9d459cc05988fc3dde6caf24 Bump extra-geom from 1.1.1 to 1.4.0 in /.github/dependabot'
+ [[ caabc5af30b2d92e9d459cc05988fc3dde6caf24 Bump extra-geom from 1.1.1 to 1.4.0 in /.github/dependabot =~ \.\*Bump\.\*from\.\*to\.\* ]]
```

So it looks like the check returned false. I think that's because of the `'` quotes around the regex, removed it and did another force push now to see if that fixes it.

2021-06-30 09:05 UTC, RobertRosca commented
Ahh almost, the script executes but it only inserted `version('1.4.0', sha256='')`

2021-06-30 09:39 UTC, RobertRosca commented
Problem was that it assumed the previous version number is the one in the url, which is not necessarily the case. Made this change:

```bash
    old_url=$(cat ./package.py | grep 'url * = *"https' -m 1 | grep -oP '"\K[^"\047]+(?=["\047])')
    old_file=$(basename -- ${old_url})
    old_version=$(echo ${old_file} | sed -e "s/.bz2//;s/.dmg//;s/.tgz//;s/.gz//;s/.zip//;s/.xz//;s/.tar//;")
```

Now the old file is pulled out of the package by greping for the first url line, and then greping for only text in quotes. The old version is then extracted from the filename by replacing common compressed file extensions with blanks.

2021-06-30 09:41 UTC, RobertRosca commented
Sweet, that looks to have worked: https://github.com/panosc-eu/spack-repo/runs/2950833495?check_suite_focus=true

2021-06-30 09:42 UTC, RobertRosca commented on .github/update-sha.sh
> +# get name and version from dependabots last commit message
```suggestion
# Script to update the SHA version

set -x

# get name and version from dependabots last commit message
```

2021-06-30 09:47 UTC, RobertRosca requested changes
With these changes it should work now, leave comments if you have any questions :smile:

2021-06-30 09:47 UTC, RobertRosca commented on .github/update-sha.sh
> +# get name and version from dependabots last commit message
Useful to see the output of each executed line in the CI logs

2021-06-30 09:47 UTC, RobertRosca commented on .github/update-sha.sh
> +if [[ $last_commit =~ '.*Bump.*from.*to.*' ]]
```suggestion
if [[ $last_commit =~ .*Bump.*from.*to.* ]]
```

Remove quotes for match to work correctly

2021-06-30 09:47 UTC, RobertRosca commented on .github/update-sha.sh
> +    old_version=$(echo $last_commit | grep -o -P '(?<=from ).*(?= to)')
```suggestion
```

Old version should be pulled out of the `package.py` file, done later

2021-06-30 09:47 UTC, RobertRosca commented on .github/update-sha.sh
> +    old_url_line=$(cat package.py | grep "url.*=.*${old_version}.*")
```suggestion
    old_url=$(cat ./package.py | grep 'url * = *"https' -m 1 | grep -oP '"\K[^"\047]+(?=["\047])')
    old_file=$(basename -- ${old_url})
    old_version=$(echo ${old_file} | sed -e "s/.bz2//;s/.dmg//;s/.tgz//;s/.gz//;s/.zip//;s/.xz//;s/.tar//;")
    old_url_line=$(cat package.py | grep "url.*=.*${old_version}.*")
```

Pull old url out from package.py, get the old filename from the old url, remove common extensions to get just the version number

2021-06-30 09:58 UTC, julianhoersch reviewed
accepted changes to make it work

2021-06-30 10:05 UTC, julianhoersch commented
Thanks! Thought it would work like that... I need to understand the regex, but the rest should be fine. :)

2021-06-30 10:36 UTC, RobertRosca commented on .github/update-sha.sh
> +
```suggestion

set -x

```

Oops, deleted this comment accidentally

2021-06-30 13:06 UTC, RobertRosca approved these changes

2021-06-30 13:07 UTC, merged